<?php
/***************************************************************************
 *
 * 	----------------------------------------------------------------------
 * 						DO NOT EDIT THIS FILE
 *	----------------------------------------------------------------------
 * 
 *  					Copyright (C) Themify
 * 						http://themifyflow.com
 *
 ***************************************************************************/

$theme_includes = apply_filters( 'tf_theme_includes',
	array( 'tf/tf-hooks.php', 'tf/tf.php', 'theme-functions.php' ) );
			
foreach ( $theme_includes as $include ) { locate_template( $include, true ); }

/*
 * Do not edit this file.
 * To add custom PHP functions to the theme, create a child theme functions.php file.
 * 
*********/
