<?php
/***************************************************************************
 *
 * 	----------------------------------------------------------------------
 * 						DO NOT EDIT THIS FILE
 *	----------------------------------------------------------------------
 * 
 *  				     Copyright (C) Themify
 * 
 *	----------------------------------------------------------------------
 *
 * 
 * Layout Hooks:
 * 
 * 		tf_hook_body_start
 * 
 * 		tf_hook_header_before
 * 		tf_hook_header_start
 * 		tf_hook_header_end
 * 		tf_hook_header_after
 * 
 * 		tf_hook_layout_before
 * 
 * 		tf_hook_content_before 
 * 		tf_hook_content_start
 * 
 * 		tf_hook_post_before
 * 		tf_hook_post_start
 *		tf_hook_post_end
 * 		tf_hook_post_after
 * 
 * 		tf_hook_comment_before
 * 		tf_hook_comment_start
 * 		tf_hook_comment_end
 * 		tf_hook_comment_after
 * 
 *		tf_hook_content_end
 * 		tf_hook_content_after
 * 
 * 		tf_hook_sidebar_before
 * 		tf_hook_sidebar_start
 * 		tf_hook_sidebar_end
 * 		tf_hook_sidebar_after
 * 
 * 		tf_hook_layout_after
 * 
 * 		tf_hook_footer_before
 * 		tf_hook_footer_start
 * 		tf_hook_footer_end
 *		tf_hook_footer_after
 * 
 *		tf_hook_body_end
 * 
 * 
***************************************************************************/

if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

/**
 * Layout Hooks
 */

function tf_hook_body_start() { 		do_action( 'tf_hook_body_start' 	);}

function tf_hook_header_before() { 		do_action( 'tf_hook_header_before' 	);}
function tf_hook_header_start() { 		do_action( 'tf_hook_header_start' 	);}
function tf_hook_header_end() { 		do_action( 'tf_hook_header_end' 	);}
function tf_hook_header_after(){ 		do_action( 'tf_hook_header_after'	);}

function tf_hook_layout_before() { 		do_action( 'tf_hook_layout_before' 	);}

function tf_hook_content_before (){		do_action( 'tf_hook_content_before' );}
function tf_hook_content_start(){ 		do_action( 'tf_hook_content_start' 	);}

function tf_hook_post_before(){ 		do_action( 'tf_hook_post_before' 	);}
function tf_hook_post_start() { 		do_action( 'tf_hook_post_start' 	);}

function tf_hook_before_post_image() { 	do_action( 'tf_hook_before_post_image' 	);}
function tf_hook_after_post_image() { 	do_action( 'tf_hook_after_post_image' 	);}

function tf_hook_before_post_title() { 	do_action( 'tf_hook_before_post_title' );}
function tf_hook_after_post_title() { 	do_action( 'tf_hook_after_post_title' 	);}

function tf_hook_before_post_content(){ do_action( 'tf_hook_before_post_content' );}
function tf_hook_after_post_content() { do_action( 'tf_hook_after_post_content'  );}

function tf_hook_post_end() { 			do_action( 'tf_hook_post_end' 		);}
function tf_hook_post_after() { 		do_action( 'tf_hook_post_after' 	);}

function tf_hook_comment_before() { 	do_action( 'tf_hook_comment_before' );}
function tf_hook_comment_start() { 		do_action( 'tf_hook_comment_start' 	);}
function tf_hook_comment_end() { 		do_action( 'tf_hook_comment_end' 	);}
function tf_hook_comment_after() { 		do_action( 'tf_hook_comment_after' 	);}

function tf_hook_content_end() { 		do_action( 'tf_hook_content_end' 	);}
function tf_hook_content_after() { 		do_action( 'tf_hook_content_after' 	);}

function tf_hook_sidebar_before(){ 		do_action( 'tf_hook_sidebar_before' );}
function tf_hook_sidebar_start (){		do_action( 'tf_hook_sidebar_start' 	);}
function tf_hook_sidebar_end(){ 		do_action( 'tf_hook_sidebar_end' 	);}
function tf_hook_sidebar_after(){ 		do_action( 'tf_hook_sidebar_after' 	);}

function tf_hook_layout_after() { 		do_action( 'tf_hook_layout_after' 	);}

function tf_hook_footer_before() { 		do_action( 'tf_hook_footer_before' 	);}
function tf_hook_footer_start() { 		do_action( 'tf_hook_footer_start' 	);}
function tf_hook_footer_end() { 		do_action( 'tf_hook_footer_end' 	);}
function tf_hook_footer_after() { 		do_action( 'tf_hook_footer_after' 	);}

function tf_hook_body_end() { 			do_action( 'tf_hook_body_end' 		);}